name: bChatManager
main: net.rymate.bchatmanager.bChatManager
depend: [ Vault ]
softdepend: [ Factions ]
version: 3.0-BETA
author: rymate1234
website: www.rymate.co.uk
description: Chat management plugin for bPermissions based of PEX ChatManager
commands:
  me:
    description: Sends a message in the third person!
    usage: /me <message>
    aliases: [m, moi]
  bchatreload:
    description: Reloads bChatManager
    usage: /bchatreload
